replicaCount: 1
image:
  repository: atlassian/jira-software
  pullPolicy: IfNotPresent
  tag: "9.4.8"
database:
  type: 'postgres72'
  url: 'jdbc://10.0.222.35:5432/jira'
  driver: 'org.postgresql.Driver'
  credentials:
    secretName: dbuser
    usernameSecretKey: username
    passwordSecretKey: password
volumes:
  localHome:
    persistentVolumeClaim:
      create: false
      storageClassName: managed-csi
      resources:
        requests:
          storage: 10Gi
    mountPath: "/var/atlassian/application-data/jira"
  sharedHome:
    persistentVolumeClaim:
      create: false
      storageClassName: my-azurefile
      resources:
        requests:
          storage: 10Gi
    mountPath: "/var/atlassian/application-data/shared-home"
    nfsPermissionFixer:
      enabled: true
      mountPath: "/shared-home"
      imageRepo: alpine
      imageTag: latest
jira:
  service:
    port: 80
    type: ClusterIP
  ports:
    http: 8080
